var circlesData = [
	{
	"ID" : "01M020", 
	"District" : "1", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "01M020", 
	"District" : "1", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "01M184", 
	"District" : "1", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "01M184", 
	"District" : "1", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "01M188", 
	"District" : "1", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "01M378", 
	"District" : "1", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "01M515", 
	"District" : "1", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "01M515", 
	"District" : "1", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "02M001", 
	"District" : "2", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "02M002", 
	"District" : "2", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "02M042", 
	"District" : "2", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "02M042", 
	"District" : "2", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "02M124", 
	"District" : "2", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "02M130", 
	"District" : "2", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "02M131", 
	"District" : "2", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "02M131", 
	"District" : "2", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "02M427", 
	"District" : "2", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "02M542", 
	"District" : "2", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "02M542", 
	"District" : "2", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "02M545", 
	"District" : "2", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "02M545", 
	"District" : "2", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "03M075", 
	"District" : "3", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "03M075", 
	"District" : "3", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "03M084", 
	"District" : "3", 
	"BackgroundColor" : "#ff9900", 
	"Language" : "French", 
	"Program" : "DL"},
	{
	"ID" : "03M084", 
	"District" : "3", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "03M087", 
	"District" : "3", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "03M145", 
	"District" : "3", 
	"BackgroundColor" : "#0099c6", 
	"Language" : "Russian", 
	"Program" : "DL"},
	{
	"ID" : "03M145", 
	"District" : "3", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "03M163", 
	"District" : "3", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "03M165", 
	"District" : "3", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "03M180", 
	"District" : "3", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "03M247", 
	"District" : "3", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "03M247", 
	"District" : "3", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "03M256", 
	"District" : "3", 
	"BackgroundColor" : "#ff9900", 
	"Language" : "French", 
	"Program" : "DL"},
	{
	"ID" : "04M057", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "04M072", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "04M072", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "04M096", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "04M112", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "04M112", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "04M155", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "04M155", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "04M155", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "04M155", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "04M182", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "04M182", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "04M182", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "04M206", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "04M372", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "04M372", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "04M435", 
	"District" : "4", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "05M129", 
	"District" : "5", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "05M161", 
	"District" : "5", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "05M200", 
	"District" : "5", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "05M200", 
	"District" : "5", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M004", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M004", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M004", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M005", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M005", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M005", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M008", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M018", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M018", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M028", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M028", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M028", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M028", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M048", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M052", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M098", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M098", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M103", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M103", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M115", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M115", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M128", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M128", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M128", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M128", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M132", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M143", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M143", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M152", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M153", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M178", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M189", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M189", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M189", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M192", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M210", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M210", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M218", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M311", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M311", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M311", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M319", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M319", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M322", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M322", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M324", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M324", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M328", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M328", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M348", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M348", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M349", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M457", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M462", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M462", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M463", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M467", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M467", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M468", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M468", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M513", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M513", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M528", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "06M540", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M552", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "06M552", 
	"District" : "6", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X001", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X005", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X018", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "07X018", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X025", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X025", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X029", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X030", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "07X049", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "07X049", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X151", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X161", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "07X179", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X223", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "07X224", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X298", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X298", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X298", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X369", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X584", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "07X584", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "07X600", 
	"District" : "7", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "08X048", 
	"District" : "8", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "08X062", 
	"District" : "8", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "08X333", 
	"District" : "8", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "08X432", 
	"District" : "8", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "08X448", 
	"District" : "8", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X011", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X011", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X022", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X028", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X028", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X053", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X053", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X055", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X058", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X070", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X070", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X073", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X109", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X114", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X117", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X117", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X126", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X163", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X170", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X199", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X218", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X218", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X219", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X232", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X232", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X274", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X294", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X311", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X311", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X313", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X325", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X339", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X365", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X412", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "09X443", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X449", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "09X454", 
	"District" : "9", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X008", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X009", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X032", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X033", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X046", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "10X046", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X046", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X054", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "10X077", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "10X080", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X085", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X085", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X086", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X086", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X091", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X094", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X094", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X095", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X118", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X118", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X205", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X207", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "10X207", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X226", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X244", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X244", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X246", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X254", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X279", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X291", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X331", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X340", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X342", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X342", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X351", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X353", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X363", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X368", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X374", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X390", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "10X390", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X391", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "10X447", 
	"District" : "10", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "11X103", 
	"District" : "11", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "11X103", 
	"District" : "11", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "11X105", 
	"District" : "11", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "11X127", 
	"District" : "11", 
	"BackgroundColor" : "#990099", 
	"Language" : "Bengali", 
	"Program" : "TBE"},
	{
	"ID" : "11X127", 
	"District" : "11", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "12X047", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "12X066", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "12X092", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "12X098", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "12X150", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "12X150", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "12X195", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "12X196", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "12X211", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "12X384", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "12X458", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "12X463", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "12X536", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "12X550", 
	"District" : "12", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "13K003", 
	"District" : "13", 
	"BackgroundColor" : "#ff9900", 
	"Language" : "French", 
	"Program" : "DL"},
	{
	"ID" : "13K009", 
	"District" : "13", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "13K020", 
	"District" : "13", 
	"BackgroundColor" : "#ff9900", 
	"Language" : "French", 
	"Program" : "DL"},
	{
	"ID" : "13K046", 
	"District" : "13", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "13K054", 
	"District" : "13", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "13K113", 
	"District" : "13", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "13K133", 
	"District" : "13", 
	"BackgroundColor" : "#ff9900", 
	"Language" : "French", 
	"Program" : "DL"},
	{
	"ID" : "13K133", 
	"District" : "13", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "14K018", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "14K034", 
	"District" : "14", 
	"BackgroundColor" : "#b82e2e", 
	"Language" : "Polish", 
	"Program" : "DL"},
	{
	"ID" : "14K050", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "14K059", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "14K071", 
	"District" : "14", 
	"BackgroundColor" : "#109618", 
	"Language" : "Yiddish", 
	"Program" : "TBE"},
	{
	"ID" : "14K084", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "14K110", 
	"District" : "14", 
	"BackgroundColor" : "#ff9900", 
	"Language" : "French", 
	"Program" : "DL"},
	{
	"ID" : "14K147", 
	"District" : "14", 
	"BackgroundColor" : "#aaaa11", 
	"Language" : "Japanese ", 
	"Program" : "DL"},
	{
	"ID" : "14K157", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "14K196", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "14K250", 
	"District" : "14", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "14K257", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "14K257", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "14K319", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "14K380", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "14K380", 
	"District" : "14", 
	"BackgroundColor" : "#109618", 
	"Language" : "Yiddish", 
	"Program" : "TBE"},
	{
	"ID" : "14K414", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "14K454", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "14K474", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "14K477", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "14K478", 
	"District" : "14", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "15K001", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "15K001", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "15K015", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "15K024", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "15K024", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "15K058", 
	"District" : "15", 
	"BackgroundColor" : "#ff9900", 
	"Language" : "French", 
	"Program" : "DL"},
	{
	"ID" : "15K088", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "15K094", 
	"District" : "15", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "15K094", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "15K094", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "15K124", 
	"District" : "15", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "15K124", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "15K131", 
	"District" : "15", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "15K131", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "15K136", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "15K169", 
	"District" : "15", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "15K169", 
	"District" : "15", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "15K169", 
	"District" : "15", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "15K169", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "15K169", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "15K230", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "15K497", 
	"District" : "15", 
	"BackgroundColor" : "#ff9900", 
	"Language" : "French", 
	"Program" : "DL"},
	{
	"ID" : "15K516", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "15K592", 
	"District" : "15", 
	"BackgroundColor" : "#dd4477", 
	"Language" : "Arabic", 
	"Program" : "TBE"},
	{
	"ID" : "15K821", 
	"District" : "15", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "16K627", 
	"District" : "16 ", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "17K189", 
	"District" : "17", 
	"BackgroundColor" : "#66aa00", 
	"Language" : "Haitian Creole", 
	"Program" : "DL"},
	{
	"ID" : "17K189", 
	"District" : "17", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "17K249", 
	"District" : "17", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "17K375", 
	"District" : "17", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "17K600", 
	"District" : "17", 
	"BackgroundColor" : "#66aa00", 
	"Language" : "Haitian Creole", 
	"Program" : "TBE"},
	{
	"ID" : "17K705", 
	"District" : "17", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "18K068", 
	"District" : "18 ", 
	"BackgroundColor" : "#66aa00", 
	"Language" : "Haitian Creole", 
	"Program" : "DL"},
	{
	"ID" : "18K276", 
	"District" : "18 ", 
	"BackgroundColor" : "#66aa00", 
	"Language" : "Haitian Creole", 
	"Program" : "DL"},
	{
	"ID" : "19K007", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "19K089", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "19K089", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "19K089", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "19K108", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "19K159", 
	"District" : "19", 
	"BackgroundColor" : "#990099", 
	"Language" : "Bengali", 
	"Program" : "TBE"},
	{
	"ID" : "19K159", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "19K171", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "19K171", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "19K214", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "19K218", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "19K290", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "19K345", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "19K507", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "19K583", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "19K583", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "19K662", 
	"District" : "19", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "20K030", 
	"District" : "20", 
	"BackgroundColor" : "#dd4477", 
	"Language" : "Arabic", 
	"Program" : "DL"},
	{
	"ID" : "20K030", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "20K069", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K105", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K112", 
	"District" : "20", 
	"BackgroundColor" : "#316395", 
	"Language" : "Italian", 
	"Program" : "DL"},
	{
	"ID" : "20K127", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K160", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K160", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K164", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K170", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "20K176", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K180", 
	"District" : "20", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "20K186", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K192", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K200", 
	"District" : "20", 
	"BackgroundColor" : "#0099c6", 
	"Language" : "Russian", 
	"Program" : "DL"},
	{
	"ID" : "20K204", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K205", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K205", 
	"District" : "20", 
	"BackgroundColor" : "#109618", 
	"Language" : "Yiddish", 
	"Program" : "TBE"},
	{
	"ID" : "20K220", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K220", 
	"District" : "20", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "20K259", 
	"District" : "20", 
	"BackgroundColor" : "#dd4477", 
	"Language" : "Arabic", 
	"Program" : "TBE"},
	{
	"ID" : "20K310", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K445", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K490", 
	"District" : "20", 
	"BackgroundColor" : "#dd4477", 
	"Language" : "Arabic", 
	"Program" : "TBE"},
	{
	"ID" : "20K490", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K490", 
	"District" : "20", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "20K503", 
	"District" : "20", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "20K505", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K505", 
	"District" : "20", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "20K506", 
	"District" : "20", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "20K506", 
	"District" : "20", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "21K090", 
	"District" : "21", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "21K097", 
	"District" : "21", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "21K101", 
	"District" : "21", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "21K225", 
	"District" : "21", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "21K228", 
	"District" : "21", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "21K228", 
	"District" : "21", 
	"BackgroundColor" : "#994499", 
	"Language" : "Hebrew", 
	"Program" : "DL"},
	{
	"ID" : "21K228", 
	"District" : "21", 
	"BackgroundColor" : "#0099c6", 
	"Language" : "Russian", 
	"Program" : "DL"},
	{
	"ID" : "21K228", 
	"District" : "21", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "21K238", 
	"District" : "21", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "21K281", 
	"District" : "21", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "21K525", 
	"District" : "21", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "21K525", 
	"District" : "21", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "21K540", 
	"District" : "21", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "22K139", 
	"District" : "22", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "22K206", 
	"District" : "22", 
	"BackgroundColor" : "#0099c6", 
	"Language" : "Russian", 
	"Program" : "DL"},
	{
	"ID" : "22K217", 
	"District" : "22", 
	"BackgroundColor" : "#6633cc", 
	"Language" : "Urdu", 
	"Program" : "TBE"},
	{
	"ID" : "24Q005", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q007", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q012", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "24Q013", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q013", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "24Q014", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "24Q014", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "24Q014", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "24Q016", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q016", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "24Q019", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q019", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q019", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "24Q028", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "24Q028", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "24Q061", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q061", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "24Q073", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q081", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q089", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q093", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q102", 
	"District" : "24", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "24Q110", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q143", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q143", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q143", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "24Q211", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q211", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q311", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q330", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "24Q455", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "24Q485", 
	"District" : "24", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "25Q020", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "25Q020", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "25Q021", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "25Q022", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "25Q024", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "25Q032", 
	"District" : "25", 
	"BackgroundColor" : "#22aa99", 
	"Language" : "Korean", 
	"Program" : "DL"},
	{
	"ID" : "25Q107", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "25Q107", 
	"District" : "25", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "25Q120", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "25Q163", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "25Q163", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "25Q163", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "25Q185", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "25Q189", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "25Q237", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "25Q241", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "25Q242", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "25Q244", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "25Q425", 
	"District" : "25", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "25Q425", 
	"District" : "25", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "25Q460", 
	"District" : "25", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "26Q162", 
	"District" : "26", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "26Q173", 
	"District" : "26", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "DL"},
	{
	"ID" : "26Q430", 
	"District" : "26", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "27Q063", 
	"District" : "27", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "27Q064", 
	"District" : "27", 
	"BackgroundColor" : "#990099", 
	"Language" : "Bengali", 
	"Program" : "TBE"},
	{
	"ID" : "27Q137", 
	"District" : "27", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "27Q197", 
	"District" : "27", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "27Q253", 
	"District" : "27", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "27Q302", 
	"District" : "27", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "27Q475", 
	"District" : "27", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "27Q480", 
	"District" : "27", 
	"BackgroundColor" : "#990099", 
	"Language" : "Bengali", 
	"Program" : "TBE"},
	{
	"ID" : "27Q480", 
	"District" : "27", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "28Q082", 
	"District" : "28", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "28Q086", 
	"District" : "28", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "28Q182", 
	"District" : "28", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "28Q182", 
	"District" : "28", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "28Q190", 
	"District" : "28", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "28Q505", 
	"District" : "28", 
	"BackgroundColor" : "#990099", 
	"Language" : "Bengali", 
	"Program" : "TBE"},
	{
	"ID" : "28Q505", 
	"District" : "28", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "29Q095", 
	"District" : "29", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "29Q095", 
	"District" : "29", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "29Q238", 
	"District" : "29", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "30Q011", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "30Q017", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q076", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q076", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "30Q092", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "30Q112", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q127", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q145", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q145", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "30Q148", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "30Q148", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "30Q149", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q150", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q152", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "30Q166", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q204", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q204", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q212", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q222", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q228", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q228", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q228", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "30Q228", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "30Q235", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "30Q280", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q329", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q445", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "30Q450", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "30Q555", 
	"District" : "30", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "30Q555", 
	"District" : "30", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "31R016", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "31R019", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "31R020", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "31R020", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "31R022", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "31R022", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "31R041", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "31R044", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "31R051", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "31R057", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "31R057", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "31R061", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "31R445", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "31R450", 
	"District" : "31", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "32K086", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "32K106", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "32K106", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "32K116", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "32K123", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "32K145", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "32K151", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "32K151", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "32K162", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "32K274", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "32K291", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "32K349", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "32K376", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "32K377", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "32K403", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "32K562", 
	"District" : "32", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75K231", 
	"District" : "75", 
	"BackgroundColor" : "#dc3912", 
	"Language" : "Chinese", 
	"Program" : "TBE"},
	{
	"ID" : "75K370", 
	"District" : "75", 
	"BackgroundColor" : "#109618", 
	"Language" : "Yiddish", 
	"Program" : "TBE"},
	{
	"ID" : "75K370", 
	"District" : "75", 
	"BackgroundColor" : "#109618", 
	"Language" : "Yiddish", 
	"Program" : "TBE"},
	{
	"ID" : "75K373", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "75K396", 
	"District" : "75", 
	"BackgroundColor" : "#109618", 
	"Language" : "Yiddish", 
	"Program" : "TBE"},
	{
	"ID" : "75K721", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75K721", 
	"District" : "75", 
	"BackgroundColor" : "#109618", 
	"Language" : "Yiddish", 
	"Program" : "TBE"},
	{
	"ID" : "75K811", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75M079", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "75M079", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75M079", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75M751", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75Q255", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75Q721", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "75Q721", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75Q721", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75Q811", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X010", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X010", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X017", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X168", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X168", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X176", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X186", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "75X186", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "DL"},
	{
	"ID" : "75X186", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X469", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X469", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X721", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X721", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X754", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X811", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X811", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "75X811", 
	"District" : "75", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "79M973", 
	"District" : "79", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"},
	{
	"ID" : "79Q950", 
	"District" : "79 ", 
	"BackgroundColor" : "#3366cc", 
	"Language" : "Spanish", 
	"Program" : "TBE"}
]

var programType1819 = [{"Width" : "46.6%",	//It's a bit silly to do this in json
				    "class" : "wrapBar", //but it's good practice!
				    "Color" : "#dc3912",
				    "Name" : "DL (46.6%)",
				    "side" : "right"},
				   {"Width" : "53.4%",
				    "class" : "wrapBar",
				    "Color" : "#3366cc",
				    "Name" : "TBE (53.4%)",
				    "side" : "left"}]

var programType1718 = [{"Width" : "44.8%",	//It's a bit silly to do this in json
				    "class" : "wrapBar", //but it's good practice!
				    "Color" : "#dc3912",
				    "Name" : "DL (44.8%)",
				    "side" : "right"},
				   {"Width" : "55.2%",
				    "class" : "wrapBar",
				    "Color" : "#3366cc",
				    "Name" : "TBE (55.2%)",
				    "side" : "left"}]

var programTypeOld = [{"Width" : "75%",
						"class" : "wrapBar",
						"Color" : "#ff9900",
						"Name" : "ESL",
						"side" : "center"},
						{"Width" : "4.7%",
						"class" : "wrapBar",
						"Color" : "#dc3912",
						"Name" : "DL",
						"side" : "center"},
						{"Width" : "12%",
						"class" : "wrapBar",
						"Color" : "#3366cc",
						"Name" : "TBE",
						"side" : "center"},
						{"Width" : "8.3%",
						"class" : "wrapBar",
						"Color" : "#109618",
						"Name" : "N/A",
						"side" : "center"}]

var districtTally = [{"district" : "District 1",
					  "Width" : "8"},
					 {"district" : "2",
					  "Width" : "13"},
					 {"district" : "3",
					  "Width" : "13"},
					 {"district" : "4",
					  "Width" : "17"},
					 {"district" : "5",
					  "Width" : "4"},
					 {"district" : "6",
					  "Width" : "66"},
					 {"district" : "7",
					  "Width" : "22"},
					 {"district" : "8",
					  "Width" : "5"},
					 {"district" : "9",
					  "Width" : "37"},
					 {"district" : "10",
					  "Width" : "43"},
					 {"district" : "11",
					  "Width" : "5"},
					 {"district" : "12",
					  "Width" : "14"},
					 {"district" : "13",
					  "Width" : "8"},
					 {"district" : "14",
					  "Width" : "21"},
					 {"district" : "15",
					  "Width" : "25"},
					 {"district" : "16",
					  "Width" : "1"},
					 {"district" : "17",
					  "Width" : "6"},
					 {"district" : "18",
					  "Width" : "2"},
					 {"district" : "19",
					  "Width" : "17"},
					 {"district" : "20",
					  "Width" : "31"},
					 {"district" : "21",
					  "Width" : "13"},
					 {"district" : "22",
					  "Width" : "3"},
					 {"district" : "24",
					  "Width" : "32"},
					 {"district" : "25",
					  "Width" : "21"},
					 {"district" : "26",
					  "Width" : "3"},
					 {"district" : "27",
					  "Width" : "9"},
					 {"district" : "28",
					  "Width" : "7"},
					 {"district" : "29",
					  "Width" : "3"},
					 {"district" : "30",
					  "Width" : "30"},
					 {"district" : "31",
					  "Width" : "14"},
					 {"district" : "32",
					  "Width" : "16"},
					 {"district" : "75",
					  "Width" : "34"},
					 {"district" : "79",
					  "Width" : "2"}]

var langBreakdown = [{"language" : "Spanish",
					"Color" : "#3366cc",
					"count" : "437"},
					{"language" : "Chinese",
					"Color" : "#dc3912",
					"count" : "70"},
					{"language" : "French",
					"Color" : "#ff9900",
					"count" : "8"},
					{"language" : "Yiddish",
					"Color" : "#109618",
					"count" : "7"},
					{"language" : "Bengali",
					"Color" : "#990099",
					"count" : "5"},
					{"language" : "Russian",
					"Color" : "#0099c6",
					"count" : "4"},
					{"language" : "Arabic",
					"Color" : "#dd4477",
					"count" : "4"},
					{"language" : "Haitian Creole",
					"Color" : "#66aa00",
					"count" : "4"},
					{"language" : "Polish",
					"Color" : "#b82e2e",
					"count" : "1"},
					{"language" : "Italian",
					"Color" : "#316395",
					"count" : "1"},
					{"language" : "Hebrew",
					"Color" : "#994499",
					"count" : "1"},
					{"language" : "Korean",
					"Color" : "#22aa99",
					"count" : "1"},
					{"language" : "Japanese",
					"Color" : "#aaaa11",
					"count" : "1"},
					{"language" : "Urdu",
					"Color" : "#6633cc",
					"count" : "1"}]

var circlesMain = d3.select('#circleContainer')										 // Begin School Circles
		.selectAll('div')
		.data(circlesData).enter()
		.append('a')
  		.attr('xlink:href', function(d){var url = 'http://site:schools.nyc.gov ';})
		.append('div')
			.attr('class', function(d) {return d.Program;})						 //class determines shape
			.style('background-color', function(d) {return d.BackgroundColor})	//color sets color
			.attr('title', function(d) { var title = d.ID;
											 title +="\n";
											 title += d.Program;
											 title +=" - ";
											 title += d.Language;

			return title;});						   //give title tag name of school

var wrapGraphTypeold = d3.select('#typeContainer2')
		.selectAll('div')
		.data(programTypeOld).enter()
		.append('div')
			.attr('class', function(d) {return d.class})
			.style('width', function(d) {return d.Width})
			.style('background-Color', function(d) {return d.Color})
			.append('div')
				.attr('title', function(d) {return d.Width})
				.text(function(d) {return d.Name})
				.style('text-align', function(d) {return d.side})
				.style('padding-left', '5px')
				.style('padding-right', '5px');			

var wrapGraphType1718 = d3.select('#typeContainer')
		.selectAll('div')
		.data(programType1718).enter()
		.append('div')
			.attr('class', function(d) {return d.class})
			.style('width', function(d) {return d.Width})
			.style('background-Color', function(d) {return d.Color})
			.append('div')
				.attr('title', function(d) {return d.Width})
				.text(function(d) {return d.Name})
				.style('text-align', function(d) {return d.side})
				.style('padding-left', '5px')
				.style('padding-right', '5px');

var wrapGraphType1819 = d3.select('#typeContainer1')
		.selectAll('div')
		.data(programType1819).enter()
		.append('div')
			.attr('class', function(d) {return d.class})
			.style('width', function(d) {return d.Width})
			.style('background-Color', function(d) {return d.Color})
			.append('div')
				.attr('title', function(d) {return d.Width})
				.text(function(d) {return d.Name})
				.style('text-align', function(d) {return d.side})
				.style('padding-left', '5px')
				.style('padding-right', '5px');

var barGraph = d3.select('#districtContainer')
		.selectAll('div')
		.data(districtTally).enter()
		.append('div')
			.attr('class', 'bar')
			.style('width', function(d) {
				var barWidth = d.Width * 15;
				return barWidth + "px"})
			.attr('title', function(d) { var title = d.Width;
				title += ' programs in district ';
				title += d.district;
				return title;})
			.text(function(d) {return d.district});

var barGraph = d3.select('#langContainer')
		.selectAll('div')
		.data(langBreakdown).enter()
		.append('div')
			.attr('class', 'bar1')
			.style('background-color', function(d) {return d.Color})
			.style('border-color', function(d) {return d.Color})
			.style('width', function(d) {
				var barWidth = d.count * 2;
				return barWidth + "px"})
			.attr('title', function(d) { var title = d.count;
				title += ' ';
				title += d.language;
				title += ' programs';
				return title;});
